Add resume page
ronaldpaek/portfolio pull request #1
Opened 2022-08-31 08:53 UTC by ronaldpaek

Added Resume Page

2022-08-31 12:00 UTC, TidbitsJS requested changes

2022-08-31 12:06 UTC, TidbitsJS commented
This refactoring will be very beneficial in the future when we'll get data from a CMS/backend. We'll be easily able to iterate/map that real data over the refactored code i.e. replacing the dummy data objects with real fetched ones @ronaldpaek

2022-09-01 10:16 UTC, ronaldpaek commented
![ezgif com-gif-maker (7)](https://user-images.githubusercontent.com/95109313/187890891-07727286-3c70-4430-a64f-4937e6f8bc8e.gif)

2022-09-01 10:18 UTC, ronaldpaek commented
![ezgif com-gif-maker (8)](https://user-images.githubusercontent.com/95109313/187891306-d9b50078-6444-4751-a00b-8ee51506bc63.gif)

2022-09-01 11:53 UTC, TidbitsJS approved these changes

2022-09-01 11:53 UTC, merged