Added dark theme, Added modal, Added scrolling Marquee, Added Red line to headers
ronaldpaek/portfolio pull request #3
Opened 2022-09-03 09:03 UTC by ronaldpaek

I am too tired, I will finish the styling tomorrow, but I will pull what I did so far.

2022-09-03 17:39 UTC, TidbitsJS requested changes

2022-09-03 17:39 UTC, TidbitsJS commented on src/pages/Portfolio.js
> +);
Create a new file PortfolioModalCard in the components folder and move this content to that file

2022-09-03 17:39 UTC, TidbitsJS commented on src/pages/Portfolio.js
>              </Box>
Create a new PortfolioCard file for this in the components folder. 

**Note: Keep the page clean and break the necessary code into separate component files**

2022-09-04 00:41 UTC, ronaldpaek commented
Was going to move all the dummy data in all components to assets but realized it doesn't work that cleanly since I would also need to import other files, so I kept it as it that's why I moved images to to images folder, but just kept it in images now.

2022-09-04 07:06 UTC, TidbitsJS approved these changes

2022-09-04 07:07 UTC, merged